tsvwg/careful-resume

draft-ietf-tsvwg-careful-resume.xml

A manual format reference to over-ride broken ID Archive reference (missing authors, noted by J.Touch).

PR ref update for Joe

---

draft-ietf-tsvwg-careful-resume.xml

This replaces application-limited and data-limited by rate-limited" as published RFC.
Closes #7

Use "rate-limited"

---

draft-ietf-tsvwg-careful-resume.xml

Fix Flight_Size

---

draft-ietf-tsvwg-careful-resume.xml

This adds some CDDL in the qlog section, and Robin Marx in the acknowledgement section.

Add CDDL and update acknowledgements

---

draft-ietf-tsvwg-careful-resume.xml

Add note that QUIC min CWND is 2 packest

Update draft-ietf-tsvwg-careful-resume for Min CWND in QUIC

---

draft-ietf-tsvwg-careful-resume.xml

Update variables in CDDL

---

draft-ietf-tsvwg-careful-resume.xml

Seeks to resolve Section 3.4 comments

Comments from JD

---

draft-ietf-tsvwg-careful-resume.xml

This update is to tidy consistency of decsription - it is not intended to change behaviour.

Tidy all actions

---

draft-ietf-tsvwg-careful-resume.xml

Careful resume Intro update

---

draft-ietf-tsvwg-careful-resume.xml

A first-cut at removing the concept of an  "endpoint token".

Changes to remove the concept of an "endpoint token".

---

draft-ietf-tsvwg-careful-resume.xml

Is this a possible alternative, to just clarify, rather than add another "if"?
( Closing #57 if this is acceptable. )

Alternative PR to #57

---

draft-ietf-tsvwg-careful-resume.xml

JD - comments to better  align implementation notes and spec. Closing issue #58 when merged

PR to try to resolve #58

---

draft-ietf-tsvwg-careful-resume.xml

Hi Christian, I checked out the section on BBR, and I really love it! It’s a useful addition. I just moved it to the implementation section since it’s more about how BBR is modified rather than the definition of Unvalidated. Let me know if you’re okay with my changes. Thanks!

Paragraphs about BBR was moved to the implementation section

---

draft-ietf-tsvwg-careful-resume.xml

This is a periodic check of grammar/spelling. This PR attmepts to bring all into one form of English.

Spell check of draft-ietf-tsvwg-careful-resume.xml

---

draft-ietf-tsvwg-careful-resume.xml

Fix editorial issues from JD

---

draft-ietf-tsvwg-careful-resume.xml

Addresses 1,2,3,4,5,6,8,9,11,12,14
Other PRs will address 7 & 10 & 13

To address NC WGLC review

---

draft-ietf-tsvwg-careful-resume.xml

Update text for transition to Unvalidated

---

draft-ietf-tsvwg-careful-resume.xml

Fix rtt_exceeded for qlog

---

draft-ietf-custura-careful-resume-qlog.xml

The added state is for when the sender uses all the jump cwnd, and starts validating what has been sent.

Added a state for unval - validating

---

draft-ietf-tsvwg-careful-resume.xml

separated congestion detected from path change.

Prep for -17

---

draft-ietf-tsvwg-careful-resume.xml

Clarify that any detectd change in path -  explicit or implicit - causes the qlog trigger.

Proposal to clarify path_change

---

draft-ietf-tsvwg-careful-resume.xml

Changed ID citation to symbolic ref

---

draft-ietf-tsvwg-careful-resume.xml

Change explanation of MMS

---

draft-ietf-tsvwg-careful-resume.xml

To address a cluster of "Lifetimes" #118

---

draft-ietf-tsvwg-careful-resume.xml

Proposed to address and closes  #119.

PR for AD Review: comments on Section 1

---

draft-ietf-tsvwg-careful-resume.xml

In the Validating Phase -> In the Unvalidated Phase

A typo in section 3.3

---

draft-ietf-tsvwg-careful-resume-qlog-01.xml

In one section the trigger was still named cwnd_limited

fix congestion_window_limited trigger name

---

careful-resume-20+
increase

Update careful-resume-20+ : PR intended to form draft-23
